apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: meet
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: webserver:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: REDIS_PASSWORD
            - name: REDIS_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_NAME
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DOMAIN
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: meet
spec:
  selector:
    app: webserver
  ports:
    - name: http
      port: 5000
      targetPort: http